[package]
name = "lockup"
version = "0.1.0"
description = "Created with Anchor"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "lockup"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
anchor-lang = { path = "../../../../lang", features = ["anchor-deprecated-state"] }
anchor-spl = { path = "../../../../spl" }
