[package]
name = "anchor-cli"
version = "0.7.0"
authors = ["armaniferrante <armaniferrante@gmail.com>"]
edition = "2018"

[[bin]]
name = "anchor"
path = "src/main.rs"

[features]
dev = []
default = []

[dependencies]
clap = "3.0.0-beta.1"
anyhow = "1.0.32"
syn = { version = "1.0.60", features = ["full", "extra-traits"] }
anchor-lang = { path = "../lang" }
anchor-client = { path = "../client" }
anchor-syn = { path = "../lang/syn", features = ["idl"] }
serde_json = "1.0"
shellexpand = "2.1.0"
serde_yaml = "0.8"
toml = "0.5.8"
serde = { version = "1.0.122", features = ["derive"] }
solana-sdk = "1.6.6"
solana-program = "1.6.6"
solana-client = "1.6.6"
serum-common = { git = "https://github.com/project-serum/serum-dex", features = ["client"] }
dirs = "3.0"
heck = "0.3.1"
flate2 = "1.0.19"
rand = "0.7.3"
which = "4.1.0"
