[package]
name = "anchor-cli"
version = "0.24.2"
authors = ["armaniferrante <armaniferrante@gmail.com>"]
rust-version = "1.56"
edition = "2021"
repository = "https://github.com/project-serum/anchor"
description = "Anchor CLI"
license = "Apache-2.0"

[[bin]]
name = "anchor"
path = "src/bin/main.rs"

[features]
dev = []
default = []

[dependencies]
clap = { version = "3.0.13", features = ["derive"] }
anyhow = "1.0.32"
syn = { version = "1.0.60", features = ["full", "extra-traits"] }
anchor-lang = { path = "../lang", version = "0.24.2" }
anchor-client = { path = "../client", version = "0.24.2" }
anchor-syn = { path = "../lang/syn", features = ["idl", "init-if-needed"], version = "0.24.2" }
serde_json = "1.0"
shellexpand = "2.1.0"
toml = "0.5.8"
semver = "1.0.4"
serde = { version = "1.0.122", features = ["derive"] }
solana-sdk = "~1.9.13"
solana-program = "~1.9.13"
solana-client = "~1.9.13"
solana-cli-config = "~1.9.13"
solana-faucet = "~1.9.13"
dirs = "3.0"
heck = "0.3.1"
flate2 = "1.0.19"
rand = "0.7.3"
tar = "0.4.35"
reqwest = { version = "0.11.4", features = ["multipart", "blocking"] }
tokio = "1.0"
pathdiff = "0.2.0"
cargo_toml = "0.9.2"
walkdir = "2.3.2"
chrono = "0.4.19"
portpicker = "0.1.1"
