[package]
name = "anchor-syn"
version = "0.19.0"
authors = ["Serum Foundation <foundation@projectserum.com>"]
repository = "https://github.com/project-serum/anchor"
license = "Apache-2.0"
description = "Anchor syntax parsing and code generation tools"
edition = "2018"

[features]
idl = []
hash = []
default = []
anchor-debug = []

[dependencies]
proc-macro2 = "1.0"
proc-macro2-diagnostics = "0.9"
quote = "1.0"
syn = { version = "1.0.60", features = ["full", "extra-traits", "parsing"] }
anyhow = "1.0.32"
heck = "0.3.1"
serde = { version = "1.0.122", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.9.2"
thiserror = "1.0"
bs58 = "0.3.1"
