[package]
name = "anchor-syn"
version = "0.25.14"
authors = ["Serum Foundation <foundation@projectserum.com>"]
repository = "https://github.com/coral-xyz/anchor"
license = "Apache-2.0"
description = "Anchor syntax parsing and code generation tools"
edition = "2021"
publish = ["star-atlas"]

[features]
init-if-needed = []
idl = []
hash = []
default = []
anchor-debug = []
seeds = []

[dependencies]
anyhow = "1.0.32"
bs58 = "0.3.1"
heck = "0.3.1"
proc-macro2 = { version = "1.0", features=["span-locations"] }
proc-macro2-diagnostics = "0.9"
quote = "1.0"
serde = { version = "1.0.122", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.9.2"
syn = { version = "1.0.60", features = ["full", "extra-traits", "parsing"] }
thiserror = "1.0"
