[package]
name = "anchor-attribute-access-control"
version = "0.25.14"
authors = ["Serum Foundation <foundation@projectserum.com>"]
repository = "https://github.com/coral-xyz/anchor"
license = "Apache-2.0"
description = "Anchor attribute macro for instruction access control"
edition = "2021"
publish = ["star-atlas"]

[lib]
proc-macro = true

[features]
anchor-debug = ["anchor-syn/anchor-debug"]

[dependencies]
anchor-syn = { path = "../../syn", version = "0.25.14", repository = "star-atlas" }
anyhow = "1.0.32"
proc-macro2 = "1.0"
quote = "1.0"
regex = "1.0"
syn = { version = "1.0.60", features = ["full"] }
