[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[[test.genesis]]
address = "FtMNMKp9DZHKWUyVAsj3Q5QV8ow4P3fUPP7ZrWEQJzKr"
program = "./target/deploy/misc.so"

[workspace]
exclude = ["programs/shared"]

[scripts]
test = "mocha -t 1000000 tests/"
