[package]
name = "anchor-attribute-account"
version = "0.25.14"
authors = ["Serum Foundation <foundation@projectserum.com>"]
repository = "https://github.com/staratlasmeta/anchor.git"
license = "Apache-2.0"
description = "Anchor attribute macro for defining an account"
edition = "2021"
publish = ["star-atlas"]

[lib]
proc-macro = true

[features]
anchor-debug = ["anchor-syn/anchor-debug"]

[dependencies]
anchor-syn = { path = "../../syn", version = "0.25.14", features = ["hash"] }
anyhow = "1.0.32"
bs58 = "0.4.0"
proc-macro2 = "1.0"
quote = "1.0"
rustversion = "1.0.3"
syn = { version = "1.0.60", features = ["full"] }
