name: No Caching Tests

on:
  push:
    branches:
      - master

jobs:
  no-caching-tests:
    name: Reusable
    uses: ./.github/workflows/reusable-tests.yaml
    with:
      cache: false
      solana_cli_version: 1.18.8
      solang_version: 0.3.2
      node_version: 18.18.0
      cargo_profile: release
      anchor_binary_name: anchor-binary-no-caching
