[package]
name = "basic-1"
version = "0.1.0"
description = "Created with Anchor"
edition = "2018"

[lib]
crate-type = ["cdylib", "lib"]
name = "basic_1"

[features]
no-entrypoint = []
cpi = ["no-entrypoint"]

[dependencies]
borsh = { git = "https://github.com/project-serum/borsh", branch = "serum", features = ["serum-program"] }
solana-program = "1.4.3"
solana-sdk = { version = "1.3.14", default-features = false, features = ["program"] }
anchor = { git = "https://github.com/project-serum/anchor", features = ["derive"] }
